name: Run Youtube Downloader Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install FFmpeg
      run: sudo apt-get install ffmpeg

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Set up bot configuration
      run: |
        echo "Change your configuration settings here" # Add your config settings

    - name: Run the bot
      run: python3 -m bot
